import { BenchmarkDiscipline } from '../types';

export const OFFICIAL_BENCHMARKS: BenchmarkDiscipline[] = [
  // --- POLICÍA NACIONAL (ESCALA BÁSICA - MUJERES) ---
  {
    id: 'cnp_suspension_barra',
    name: 'Suspensión en Barra Asimétrica / Isométrica',
    targetExam: 'policia_nacional',
    vector: 'trac',
    unit: 'segundos',
    description:
      'Posición isométrica con brazos flexionados, palmas hacia atrás y barbilla por encima de la barra sin apoyarse. Adaptado progresivamente desde apoyo de pies y bandas elásticas hasta libre.',
    higherIsBetter: true,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 18,
    history: [
      { date: '2026-08-20', value: 8, points: 0 },
      { date: '2026-09-04', value: 18, points: 0 },
    ],
    officialTableFemale: [
      { points: 1, markText: '36s', value: 36 },
      { points: 2, markText: '38s', value: 38 },
      { points: 3, markText: '40s', value: 40 },
      { points: 4, markText: '42s', value: 42 },
      { points: 5, markText: '44s (Aprobado Oficial)', value: 44 },
      { points: 6, markText: '52s', value: 52 },
      { points: 7, markText: '61s', value: 61 },
      { points: 8, markText: '71s', value: 71 },
      { points: 9, markText: '82s', value: 82 },
      { points: 10, markText: '95s (Nota Máxima)', value: 95 },
    ],
  },
  {
    id: 'cnp_circuito_agilidad',
    name: 'Circuito de Agilidad y Coordinación',
    targetExam: 'policia_nacional',
    vector: 'agi',
    unit: 'segundos',
    description:
      'Recorrido oficial de agilidad con vallas y postes con salidas y giros rápidos. Recreado y delimitado en parcela.',
    higherIsBetter: false,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 13.5,
    history: [
      { date: '2026-08-20', value: 15.2, points: 0 },
      { date: '2026-09-04', value: 13.5, points: 0 },
    ],
    officialTableFemale: [
      { points: 1, markText: '12.8s', value: 12.8 },
      { points: 2, markText: '12.4s', value: 12.4 },
      { points: 3, markText: '12.0s', value: 12.0 },
      { points: 4, markText: '11.6s', value: 11.6 },
      { points: 5, markText: '11.2s (Aprobado Oficial)', value: 11.2 },
      { points: 6, markText: '10.8s', value: 10.8 },
      { points: 7, markText: '10.4s', value: 10.4 },
      { points: 8, markText: '10.0s', value: 10.0 },
      { points: 9, markText: '9.6s', value: 9.6 },
      { points: 10, markText: '9.3s (Nota Máxima)', value: 9.3 },
    ],
  },
  {
    id: 'cnp_carrera_1000m',
    name: 'Resistencia Aeróbica - 1.000 metros',
    targetExam: 'policia_nacional',
    vector: 'res',
    unit: 'segundos (mm:ss)',
    description:
      'Carrera continua de 1.000 metros lisos. Puede realizarse en campo abierto / caminos de tierra (amortiguación natural óptima) o en parcela de ~300 m² (14 vueltas al perímetro). Progresión inicial mediante método CACO.',
    higherIsBetter: false,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 320,
    history: [
      { date: '2026-08-20', value: 360, points: 0 },
      { date: '2026-09-04', value: 320, points: 0 },
    ],
    officialTableFemale: [
      { points: 1, markText: '5:00 min (300s)', value: 300 },
      { points: 2, markText: '4:51 min (291s)', value: 291 },
      { points: 3, markText: '4:43 min (283s)', value: 283 },
      { points: 4, markText: '4:35 min (275s)', value: 275 },
      { points: 5, markText: '4:27 min (267s) (Aprobado)', value: 267 },
      { points: 6, markText: '4:17 min (257s)', value: 257 },
      { points: 7, markText: '4:06 min (246s)', value: 246 },
      { points: 8, markText: '3:56 min (236s)', value: 236 },
      { points: 9, markText: '3:46 min (226s)', value: 226 },
      { points: 10, markText: '3:36 min (216s) (Máximo)', value: 216 },
    ],
  },

  // --- GUARDIA CIVIL (BAREMO OFICIAL FEMENINO 30-34 AÑOS) ---
  {
    id: 'gc_flexiones_suelo',
    name: 'Potencia Tren Superior - Flexiones en Suelo',
    targetExam: 'guardia_civil',
    vector: 'emp',
    unit: 'repeticiones',
    description:
      'Extensiones de brazos en suelo con barbilla tocando taco de 6 cm y cuerpo alineado. Inicio con flexiones en pared y banco elevado.',
    higherIsBetter: true,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 5,
    history: [
      { date: '2026-08-20', value: 2, points: 0 },
      { date: '2026-09-04', value: 5, points: 0 },
    ],
    officialTableFemale: [
      { points: 1, markText: '7 reps', value: 7 },
      { points: 2, markText: '8 reps', value: 8 },
      { points: 3, markText: '9 reps', value: 9 },
      { points: 4, markText: '10 reps', value: 10 },
      { points: 5, markText: '11 reps (APTO Oficial GC)', value: 11 },
      { points: 6, markText: '12 reps', value: 12 },
      { points: 7, markText: '13 reps', value: 13 },
      { points: 8, markText: '14 reps', value: 14 },
      { points: 9, markText: '15 reps', value: 15 },
      { points: 10, markText: '16+ reps (Sobresaliente)', value: 16 },
    ],
  },
  {
    id: 'gc_velocidad_60m',
    name: 'Velocidad - 60 metros Lisos',
    targetExam: 'guardia_civil',
    vector: 'res',
    unit: 'segundos',
    description:
      'Salida en pie y aceleración máxima en 60 metros. Recreado en recta de parcela con medición de zancada.',
    higherIsBetter: false,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 12.8,
    history: [
      { date: '2026-08-20', value: 14.2, points: 0 },
      { date: '2026-09-04', value: 12.8, points: 0 },
    ],
    officialTableFemale: [
      { points: 1, markText: '12.4s', value: 12.4 },
      { points: 2, markText: '12.1s', value: 12.1 },
      { points: 3, markText: '11.8s', value: 11.8 },
      { points: 4, markText: '11.5s', value: 11.5 },
      { points: 5, markText: '11.2s (APTO Oficial)', value: 11.2 },
      { points: 6, markText: '10.8s', value: 10.8 },
      { points: 7, markText: '10.5s', value: 10.5 },
      { points: 8, markText: '10.2s', value: 10.2 },
      { points: 9, markText: '10.0s', value: 10.0 },
      { points: 10, markText: '9.8s (Máximo)', value: 9.8 },
    ],
  },
  {
    id: 'gc_resistencia_2000m',
    name: 'Resistencia Aeróbica - 2.000 metros',
    targetExam: 'guardia_civil',
    vector: 'res',
    unit: 'segundos (mm:ss)',
    description:
      'Carrera continua de 2.000 metros. Realizable en campo / caminos de tierra o en parcela de ~300 m² (28 vueltas al perímetro). Exige gestión del umbral aeróbico y respiración rítmica.',
    higherIsBetter: false,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 810,
    history: [
      { date: '2026-08-20', value: 890, points: 0 },
      { date: '2026-09-04', value: 810, points: 0 },
    ],
    officialTableFemale: [
      { points: 1, markText: '12:30 min (750s)', value: 750 },
      { points: 2, markText: '12:10 min (730s)', value: 730 },
      { points: 3, markText: '11:50 min (710s)', value: 710 },
      { points: 4, markText: '11:30 min (690s)', value: 690 },
      { points: 5, markText: '11:15 min (675s) (APTO)', value: 675 },
      { points: 6, markText: '10:45 min (645s)', value: 645 },
      { points: 7, markText: '10:15 min (615s)', value: 615 },
      { points: 8, markText: '9:50 min (590s)', value: 590 },
      { points: 9, markText: '9:35 min (575s)', value: 575 },
      { points: 10, markText: '9:20 min (560s) (Máximo)', value: 560 },
    ],
  },

  // --- BOMBEROS COMUNIDAD / AYUNTAMIENTO DE MADRID (ADAPTADO A MATERIAL) ---
  {
    id: 'bomberos_dominadas_traccion',
    name: 'Tracción en Barra Fija (Dominadas estrictas)',
    targetExam: 'bomberos_madrid',
    vector: 'trac',
    unit: 'repeticiones',
    description:
      'Dominadas pronadas completas con barbilla sobre barra y extensión total de codos. Nivel inicial con elástico grueso de 35kg.',
    higherIsBetter: true,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 1,
    history: [
      { date: '2026-08-20', value: 0, points: 0 },
      { date: '2026-09-04', value: 1, points: 1 },
    ],
    officialTableFemale: [
      { points: 1, markText: '1 rep', value: 1 },
      { points: 2, markText: '2 reps', value: 2 },
      { points: 3, markText: '3 reps', value: 3 },
      { points: 4, markText: '3.5 reps', value: 3.5 },
      { points: 5, markText: '4 reps (Aprobado)', value: 4 },
      { points: 6, markText: '6 reps', value: 6 },
      { points: 7, markText: '8 reps', value: 8 },
      { points: 8, markText: '10 reps', value: 10 },
      { points: 9, markText: '11 reps', value: 11 },
      { points: 10, markText: '12+ reps (Nota Máxima)', value: 12 },
    ],
  },
  {
    id: 'bomberos_fondos_paralelas',
    name: 'Fondos en Barras Paralelas y Empuje',
    targetExam: 'bomberos_madrid',
    vector: 'emp',
    unit: 'repeticiones',
    description:
      'Flexión de codos a 90 grados y extensión completa en barras paralelas. Iniciación con descarga elástica.',
    higherIsBetter: true,
    passScoreCutoff: 5,
    isUnlockedHeroic: false,
    currentMark: 3,
    history: [
      { date: '2026-08-20', value: 1, points: 0 },
      { date: '2026-09-04', value: 3, points: 1 },
    ],
    officialTableFemale: [
      { points: 1, markText: '3 reps', value: 3 },
      { points: 2, markText: '4 reps', value: 4 },
      { points: 3, markText: '6 reps', value: 6 },
      { points: 4, markText: '7 reps', value: 7 },
      { points: 5, markText: '8 reps (Aprobado)', value: 8 },
      { points: 6, markText: '10 reps', value: 10 },
      { points: 7, markText: '12 reps', value: 12 },
      { points: 8, markText: '14 reps', value: 14 },
      { points: 9, markText: '16 reps', value: 16 },
      { points: 10, markText: '18+ reps (Nota Máxima)', value: 18 },
    ],
  },
];
